# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bed4f9539badc6a85df3e1eb74f52e850986fa98c03cdf37eb1a70b742e9fca590422001905112c087640ad9c7243ce40a495fb1a3e1d4c6d2fc15435719612c

test:
  secret_key_base: fd51acf20fcb6b300aef9018c2efcdf39d58f5d3f2fe6f87ce3b222dc2909e402a5d9fc031d0947b34c96a6d6edae2187003f9f68551b6984922e4952b941686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
